imports:
    - { resource: ../../../TestBundle/Resources/config/twig.yml }
    - { resource: services/frontend-installer.yaml }

services:
    CoreShop\Bundle\FrontendBundle\Command\InstallFrontendCommand:
        parent: CoreShop\Bundle\CoreBundle\Command\InstallResourcesCommand
        arguments:
            $frontendInstaller: '@CoreShop\Bundle\FrontendBundle\Installer\FrontendInstallerInterface'
        tags:
            - { name: console.command, command: coreshop:frontend:install }

    coreshop.frontend.controller.abstract:
        class: CoreShop\Bundle\FrontendBundle\Controller\FrontendController
        abstract: true
        calls:
            - [setContainer, ['@service_container']]

    CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfiguratorInterface: '@CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfigurator'
    CoreShop\Bundle\FrontendBundle\TemplateConfigurator\TemplateConfigurator:
        public: true
        arguments:
            - '%coreshop.frontend.view_prefix%'
            - '%coreshop.frontend.view_suffix%'

    CoreShop\Bundle\FrontendBundle\Twig\LocaleSwitcherExtension:
        arguments:
            - '@Pimcore\Model\Document\Service'
            - '@CoreShop\Component\Core\Context\ShopperContextInterface'
            - '@Symfony\Component\HttpFoundation\RequestStack'
            - '@router'
        tags:
            - { name: twig.extension }

    CoreShop\Bundle\FrontendBundle\Twig\WishlistExtension:
        arguments:
            $wishlistContext: '@coreshop.context.storage_list.wishlist'
        tags:
            - { name: twig.extension }

    CoreShop\Bundle\FrontendBundle\Twig\MergeRecursiveExtension:
        tags:
            - { name: twig.extension }

    CoreShop\Bundle\FrontendBundle\Twig\TypeCastExtension:
        tags:
            - { name: twig.extension }

    CoreShop\Bundle\FrontendBundle\Controller\Extend\CartWidgetController:
        arguments:
            $shopperContext: '@CoreShop\Component\Core\Context\ShopperContextInterface'
            $container: '@service_container'
        tags: [ 'controller.service_arguments' ]
